# Generated by Django 2.2.7 on 2020-01-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Event', max_length=50),
        ),
        migrations.AddField(
            model_name='timeline',
            name='pub_date',
            field=models.DateTimeField(default='Now', verbose_name='Date published'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='title',
            field=models.CharField(default='New Timeline', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default='Now', verbose_name='Date published'),
        ),
    ]
