# Generated by Django 3.0.2 on 2020-01-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200107_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
