# Generated by Django 3.0.2 on 2020-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='event',
            new_name='events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='2020-01-01 06:00', verbose_name='Date'),
        ),
    ]
